name: rupp_student_conference_mobile
description: A Flutter version of the RUPP Student Conference & Opportunity Platform.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^16.0.0

  # Networking
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # JSON Annotation
  json_annotation: ^4.9.0

  # Loading
  flutter_spinkit: ^5.2.1

  # SVG
  flutter_svg: ^2.2.0

  # Cached Images
  cached_network_image: ^3.4.1

  # Date Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/